### ISSUE TITLE
Feature request: Automatic Resizing

### ISSUE THREAD

**Issue by pigsflew** [GoldenChrysus/ffxiv-ember-overlay#39]
**Describe the feature you'd like**
I'd love if the overlay would automatically resize its height (up to a maximum)

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
Custom CSS:

```css
#root {
  height: auto;
}
#container #inner #content {
  font-size: 20px;
  max-height: calc(12em + 0.9em);
}
```

This sets a max height that shows 12 display rows plus the shorter header before the inner container becomes scrollable. Of course, this is not for the timers feature & probably won't work properly there :)

**Comment by GoldenChrysus** [comment]
This would break the collapsing feature. Additionally, the overlay already resizes its height to the height of the OverlayPlugin window, so I'm not sure I follow with the intent of the request. Essentially, if you find that your overlay is too small or too big, it's most likely because your OverlayPlugin window for the overlay is too small or too big, so you can resize it.

**Comment by pigsflew** [comment]
It doesn't seem to break the collapsing feature; the collapse feature only shows my parse and no footer.

This change just means that there is no empty space between the end of the party list in normal mode and the footer, so to waste less screen real-estate while still showing my whole party's output.

The max-height means that the element will never expand to longer than that high (12.9ems at 20px per em, or 258px), this prevents it from covering up other bits of my HUD when I'm in a 24-man or a duty with lots of NPC allies.

Here's what it looks like in action:

https://user-images.githubusercontent.com/868821/119606149-dde62380-bda6-11eb-9bd4-b0bb77d8eece.mp4

**Comment by pigsflew** [comment]
A slight improvement is to just set the inner-content max height to 100vh:

```css
#root {
  height: auto;
}
#container #inner #content {
  max-height: 100vh;
}
```

This means that once you click into a player's info, it expands to the max height of the overlay window, but on a normal table, it'll collapse down to the minimum size it needs to be.

**Comment by GoldenChrysus** [comment]
It does break collapse; you haven't tested with all feasible setting combinations. If you enable downward collapsing and have a combatant list loaded, the overlay shifts downwards by whatever extra "gap" there is between the bottom of the combatant table to the navigation footer. No user interaction with the overlay other than physically dragging it should ever cause it to move.

Additionally, your change breaks all the navigation buttons:
![image](https://user-images.githubusercontent.com/17366720/119625481-38e43e80-bdd8-11eb-8412-746582f5ab7e.png)
![image](https://user-images.githubusercontent.com/17366720/119625489-3b469880-bdd8-11eb-9128-e4d3a9507b18.png)

The overlay must never extend beyond the bounds of the OverlayPlugin window, which is what your CSS is causing it to do.

As far as the original CSS, definitely don't want any font size changes. It causes all the text from the start up screen to other texts to be significantly larger than they should. Additionally, container dimensions should be based on percentages and pixels rather than localized font sizes which could change at any time (including due to other custom CSS).

Lastly, this would of course have to be implemented as a localized setting, as no new functionality should ever disrupt or interfere with how users expect (or have grown accustomed to) the overlay to behave. So I can keep this on the list of potential features, but no one else has ever requested it, and each setting requires work from eight translators. For now, you have said your own CSS accomplishes what your goal is: "I'd love if the overlay would automatically resize its height (up to a maximum)"

**Comment by pigsflew** [comment]
Sorry. In my defense, I *did* put the custom css in the "alternate solutions I have tried" field.

Ultimately I spent 2 seconds on a proof of concept workaround and filed a feature request, not a pull request; it seems like you're really expecting me to have developed the feature myself. I get that you have to put mutually incompatible settings behind settings flags, because that's just how this kind of thing works, and Ember Overlay already has some settings like that.

I have not dug into the existing code except to look at the existing CSS for the five seconds it took to find `#root` and `#content` elements to style.

I'm just fine with this being on your backlog, no worries, I get that it's a labor of love. Maybe I'm misreading your response as defensiveness, but I'm not trying to attack you or anything, just requesting a feature *I* wish it had, so that I can fit it in around all of the other UI elements that *I* use. I can't know what anyone else wants. I appreciate the plugin itself, very much.

**Comment by tylercrompton** [comment]
I'd like this feature too, as it is a solution to two of my wishes: to not have to scroll and to not have it take up unnecessary screen real estate. I tried @pigsflew's CSS suggestion but setting aside the mentioned problems with that approach, I still found that it doesn't work for my purposes because it causes the window to grow/shrink downward. In my use case, my overlay is at the bottom of the screen, so I'd want it to grow/shrink upward.

**Comment by SmoothJaz** [comment]
Agreed, I would also like to have this feature and would like it to expand upwards as @[tylercrompton](https://github.com/tylercrompton) stated

**Comment by GoldenChrysus** [comment]
There are no plans to implement this feature; as mentioned, there are far too many circumstances to consider to make this worth the development time. Someone else is free to contribute this if they wish.
