### ISSUE TITLE
Hide Limit Break from Irrelevant Player Tables

### ISSUE THREAD

**Issue by tylercrompton** [GoldenChrysus/ffxiv-ember-overlay#41]
**Describe the feature you'd like**
Limit Break has multiple uses. But each use is limited to a single purpose. Sometimes, it's simply not relevant in some player tables. Currently, the overlay always displays Limit Break in the DPS, heal, and tank player tables. However, this isn't necessary. For example, if Limit Break is only used for DPS, then it's wasting space in the heal and tank player tables. Due to the nature of Limit Break, any reasonable person would safely assume that its omission from a player table would signify that it wasn't used for the purpose corresponding to that player table.

**Is your feature request related to a problem? Please describe.**
It clutters up some of the player tables.

**Describe alternatives you've considered**
One alternative solution that I considered is to suggest hiding entries from the player tables as follow:

- Entities that do zero damage should be hidden from the DPS player table.
- Entities that do zero heals should be hidden from the heal player table.
- Entities that take zero damage and block zero damage should be hidden from the tank player table.

However, in some cases, this would hide relevant information. For example, if a DPS player does no damage, then that should most certainly be displayed. So I ruled out this potential solution.

**Additional context**
No additional context is necessary.

**Comment by GoldenChrysus** [comment]
From combatant data, it is not possible to determine which type of LB is used. The effective output cannot be considered as it is possible to use a LB incorrectly or inefficiently (e.g. using an AOE LB on nothing). The LB should still appear in such situations as it was a combatant even if it did not contribute anything useful due to player error -- as some may consider this important information.
